### ISSUE TITLE
Azurra Wiki: naming sample project: Canje/Ganje

### ISSUE THREAD

**Issue by ssepan2** [Elbullazul/Azurra_framework#2]
Pages 2, 3 (2 places) of the wiki call the sample project Canje; page 5 calls it Ganje (3 places) as do 6, 7, 8

**Comment by ssepan2** [comment]
Actually, page  3 uses 'C' 2x in step 2, and uses 'G' in step 4.

**Comment by Elbullazul** [comment]
fixed, renamed to ganje in all places

**Comment by ssepan2** [comment]
Looks good!
